config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/parts', to: 'static_pages#parts'
  get '/service', to: 'static_pages#service'
  get '/trailers', to: 'static_pages#trailers'
  get '/trucks', to: 'static_pages#trucks'
  get '/contact', to: 'static_pages#contact'
  get '/dyno', to: 'static_pages#dyno'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def parts
  end
  def service
  end
  def trailers
  end
  def trucks
  end
  def contact
  end
  def dyno
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id='footer'>
		<footer>
			<p id='footertext'>&copyCopyright 2016 Midwest Diesel Service Inc, All Rights Reserved.</p>
			<div id='facebook'>
			<a href='https://www.facebook.com/Midwest-Diesel-Service-858550757491313/'><%= image_tag("facebook.png", alt: "Midwest Diesel Facebook", :size => "40x40" ) %></a>
			</div>
		</footer>
		</div>

app/views/layouts/_header.html.erb
<div id='header'>
	<div id='top-logos'></div>
		<%= image_tag("mwd_service_logo2.png", alt: "Midwest Diesel Service", :id => 'logo') %>
		<%= image_tag("Logo Header.jpg", alt: "Dealership", :id => 'shingle') %> 
		<div id='address'>
			<p style='float: right'>8284 West 35W Service Drive NE<br>Minneapolis, MN 55449<br>(763) 780-8533</p>
		</div>
	</div>
				
		<nav style='color:white'>
			<div class="nav-bar">
				<ul id="horizontal-list" style="list-style:none">
					<li class=nav><%= link_to "Home", root_path %></li> 
					<li class=nav><%= link_to "Parts", parts_path %></li> 
					<li class=nav><%= link_to "Service", service_path %></li> 
					<li class=nav><%= link_to "Dyno", dyno_path %></li> 
					<li class=nav><%= link_to "Trailers", trailers_path %></li> 
					<li class=nav><%= link_to "Trucks", trucks_path %></li>
					<li class=nav><%= link_to "Contact", contact_path %></li> 
				</ul>
			</div>
		</nav>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MidwestDiesel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
    	<%= yield %>
    	
    	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div id='body' style='min-height:0px;'>
		<%= image_tag("IMG_2291.jpg", alt: "Home", :size => "750x470", :id => "jumbotron", :class => "jumbotron") %>

	<div id=about><h1>About Us</h1>
		<div id=info>
			<p>Midwest Diesel Service, located in Minneapolis, MN, has been serving the twin cities trucking industry for over 30 years. 
			We are family owned and operated and our mechanics have over 100 years of combined diesel experience. </p>
			<p>We are an authorized OEM Dealer for Caterpillar, Cummins, and Detroit engines and repairs as well as a dealer 
			for Crane Carrier Trucks and Landoll Trailers.</p>
			<p>Why you should take your truck to us:</p>
			<ul>
				<li>We build great relationships with our customers</li>
				<li>Knowledgeable and experienced staff</li>
				<li>Our mechanics are trained by OEM manufacturers</li>
				<li>We only sell the highest quality OEM parts</li>
				<li>We'll work with your budget</li>
				<li>In certain cases, financing can be available</li>
			</ul>
			
			<p>Give us a call at 763-780-8533 to setup your next truck service.</p>
			
			</div>
		</div>
	</div>

app/views/static_pages/parts.html.erb
<div id='body'>
	
		<img id=jumbotron class='jumbotron' style='float: left' src='..\Images\img_2297.jpg' width='750px' height='470px'>
		<%= image_tag("IMG_2297.jpg", alt: "Parts", :id => 'jumbotron', :class => "jumbotron", :size => "750x470")%>
		<div id=about><h1>OEM Parts</h1>
			<div id=info>
				<p>We carry a large selection of OEM parts at excellent prices.  Our experienced staff will make sure you get the parts you need 
				for the best possible price.  Often we can source used parts to save you even more money.</p>
				<p>Here are just a few of the OEM certified brands of parts that we carry:</p>
				<ul>
					<li>Caterpillar</li>
					<li>Cummins</li>
					<li>Detroit</li>
					<li>Freightliner</li>
					<li>Western Star</li>
					<li>Landoll</li>
					<li>Crane Carrier</li>
					<li>And more!</li>
				</ul>
				<p>We sell everything from oil filters to overhaul kits.</p>
			</div>
		</div>
	</div>